-- ============================================================================
-- IDC Platform — Dunning & Notification System Migration
-- Migration ID: 006_dunning
-- Description: Adds notification_events table for WebSocket push, dunning
--              system config keys, and invoice-related permissions.
-- ============================================================================

-- --------------------------------------------------------------------------
-- B.10.1  Notification Events (for WebSocket push)
-- --------------------------------------------------------------------------
-- Stores events generated by the dunning system and other business processes.
-- The WebSocket notification handler reads from this table to push events
-- to distributors in real-time.

CREATE TABLE notification_events (
    id              BIGSERIAL PRIMARY KEY,
    distributor_id  BIGINT NOT NULL,
    type            VARCHAR(64) NOT NULL,        -- invoice.overdue | invoice.reminder | invoice.paid | subscription.suspended | subscription.terminated
    title           VARCHAR(256) NOT NULL,
    message         TEXT,
    data            JSONB,                       -- event-specific payload (e.g. { invoice_id: 1, amount: "1200.00" })
    is_read         BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_nev_distributor ON notification_events(distributor_id);
CREATE INDEX idx_nev_type ON notification_events(type);
CREATE INDEX idx_nev_read ON notification_events(is_read);
CREATE INDEX idx_nev_created ON notification_events(created_at DESC);

ALTER TABLE notification_events ADD CONSTRAINT fk_nev_distributor
    FOREIGN KEY (distributor_id) REFERENCES distributors(id);

-- --------------------------------------------------------------------------
-- A.8.3  Dunning system config keys
-- --------------------------------------------------------------------------
-- These supplement the dunning keys already seeded in 001_init.sql.
-- Existing keys from seed data:
--   dunning.reminder_days_before  = '3'    (days before due to send reminder)
--   dunning.reminder_overdue_days = '1,3,7' (days after due for reminders)
-- Existing billing config (used by dunning):
--   billing.auto_suspend_days     = '15'   (overdue → suspend after N days)
--   billing.auto_terminate_days   = '30'   (overdue → terminate after N days)

INSERT INTO system_config (key, value, description) VALUES
    ('dunning.enabled', 'true', '启用催缴系统'),
    ('dunning.batch_size', '50', '催缴每次处理账单数量'),
    ('dunning.reminder_overdue_1', '1', '逾期第1天提醒'),
    ('dunning.reminder_overdue_2', '3', '逾期第3天提醒'),
    ('dunning.reminder_overdue_3', '7', '逾期第7天提醒'),
    ('dunning.suspend_after_days', '15', '逾期N天后暂停服务'),
    ('dunning.terminate_after_days', '30', '逾期N天后终止服务'),
    ('dunning.suspend_notify_template', '您的账单 ${invoice_no} 已逾期 ${overdue_days} 天，服务将被暂停。请尽快登录平台完成支付。', '逾期暂停通知模板'),
    ('dunning.terminate_notify_template', '您的账单 ${invoice_no} 已逾期 ${overdue_days} 天，服务将被终止。如有疑问请联系客服。', '逾期终止通知模板'),
    ('dunning.reminder_notify_template', '您的账单 ${invoice_no} 将于 ${due_date} 到期，金额 ${amount} 元。请确保账户余额充足。', '到期提醒通知模板'),
    ('dunning.overdue_notify_template', '您的账单 ${invoice_no} 已逾期，逾期金额 ${amount} 元，请尽快支付避免服务暂停。', '逾期通知模板')
ON CONFLICT (key) DO NOTHING;

-- --------------------------------------------------------------------------
-- B.7.1  Additional invoice permissions
-- --------------------------------------------------------------------------

INSERT INTO permissions (code, name, module) VALUES
    ('invoice:generate', '生成账单', 'invoice'),
    ('invoice:export', '导出账单', 'invoice'),
    ('dunning:run', '执行催缴', 'dunning')
ON CONFLICT (code) DO NOTHING;

-- Grant all new permissions to admin
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'admin'
  AND p.code IN ('invoice:generate', 'invoice:export', 'dunning:run')
ON CONFLICT DO NOTHING;
